# Configuration for scrapers

# Mode configuration
# Available modes:
# - scrape-only: Only scrapes assignments without merging and uploading
# - scrape-and-upload: Scrapes assignments and performs merge and upload process
mode: "scrape-and-upload"

# Graphy Assignment Scraper configuration
graphy_assignment_scraper:
  email: "your_email@example.com"
  password: "your_password"
  # assignment_id: "meta" 
  assignment_id: 
    - "67ac42592413734ddbf532f6"
    - "67ac40d146c5d24ad783e876"
    - "67ac4ecdeca28c2919760bb8"
    - "67ac438e9958f50ef5960ed7"
  # You can add more assignment IDs as needed

# Supabase configuration
supabase:
  url: "https://your-project-id.supabase.co"
  key: "your-supabase-service-key"
  table: "your_table_name"
  schema: "public"  # optional, default is "public"